Readd lighthouse.

diff --git a/.github/workflows/post-deploy.yaml b/.github/workflows/post-deploy.yaml
--- a/.github/workflows/post-deploy.yaml
+++ b/.github/workflows/post-deploy.yaml
@@ -7,11 +7,11 @@ on:
     branches-ignore:
       - 'master'
 
-# env:
-#     ACC_MIN: 0.80
-#     BPR_MIN: 0.90
-#     PRF_MIN: 0.90
-#     SEO_MIN: 0.85
+env:
+    ACC_MIN: 0.80
+    BPR_MIN: 0.90
+    PRF_MIN: 0.90
+    SEO_MIN: 0.85
 
 jobs:
     build:
@@ -69,36 +69,37 @@ jobs:
               with:
                 sites: '["${{ needs.build.outputs.env_url }}"]'
                 expected: '[301]'
-    # audit:
-    #     name: 'Lighthouse Audit'
-    #     runs-on: ubuntu-latest
-    #     needs: build
-    #     outputs:
-    #         audit_data: ${{ steps.report.outputs.report_data }}
-    #     steps:
-    #         - name: Audit live URL
-    #           uses: jakejarvis/lighthouse-action@master
-    #           with:
-    #             url: ${{ needs.build.outputs.env_url }}admin
-    #         - name: Upload results as an artifact
-    #           uses: actions/upload-artifact@master
-    #           with:
-    #             name: report
-    #             path: './report'
-    #         - name: Pass report data
-    #           id: report
-    #           run: |
-    #               export REPORT=$(ls report | grep \.json$)
-    #               echo "Download the full report under *Artifacts* at: https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
-    #               echo "::set-output name=report_data::$REPORT"
-    #         - name: SEO test
-    #           run: |
-    #               REPORT=$(ls report | grep \.json$)
-    #               SCORE=$(cat report/$REPORT | jq -r '.categories.seo.score')
-    #               if [ 1 -eq "$(echo "${SCORE} < ${{ env.SEO_MIN }}" | bc)" ]; then
-    #                   echo "Threshold Failed. Download the full report under *Artifacts* at: https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
-    #                   exit 1
-    #               fi
+    audit:
+        name: 'Lighthouse Audit'
+        runs-on: ubuntu-latest
+        needs: build
+        if: needs.build.outputs.integration_status == 'platformsh'
+        outputs:
+            audit_data: ${{ steps.report.outputs.report_data }}
+        steps:
+            - name: Audit live URL
+              uses: jakejarvis/lighthouse-action@master
+              with:
+                url: ${{ needs.build.outputs.env_url }}admin
+            - name: Upload results as an artifact
+              uses: actions/upload-artifact@master
+              with:
+                name: report
+                path: './report'
+            - name: Pass report data
+              id: report
+              run: |
+                  export REPORT=$(ls report | grep \.json$)
+                  echo "Download the full report under *Artifacts* at: https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
+                  echo "::set-output name=report_data::$REPORT"
+            - name: SEO test
+              run: |
+                  REPORT=$(ls report | grep \.json$)
+                  SCORE=$(cat report/$REPORT | jq -r '.categories.seo.score')
+                  if [ 1 -eq "$(echo "${SCORE} < ${{ env.SEO_MIN }}" | bc)" ]; then
+                      echo "Threshold Failed. Download the full report under *Artifacts* at: https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
+                      exit 1
+                  fi
     # audit-test:
     #     runs-on: ubuntu-latest
     #     name: 'Lighthouse Tests'
